### ISSUE TITLE
pip not respecting dependencies in TOML file

### ISSUE THREAD

**Issue by brown170** [brown170/x4i#22]
Observed on two separate macOS machines running homebrew managed python 3.10+ installations.  pip installs were not processing dependencies in the TOML file nor was it following the dependency chain from the requirements.txt file.  The requirements.txt file itself would be processed using `pip -r`, but only dependencies explicitly listed in the requirements.txt file were included.  Previous versions of pip would attempt to reconcile the implied dependencies.

**Comment by julia-sprenger** [comment]
Hi @brown170, I tested installation with dependencies specified in the toml file on a ubuntu system and there it works fine with pip version 24.0.
I think for the user the installation should be in any case from a package index. Would you mind if I propose a release mechanism to make this package available on PyPI? This way the user installation should be independent on how the package is build and the location of dependency definition.

**Comment by julia-sprenger** [comment]
Or are you already releasing the package under a different name on PyPI: https://pypi.org/project/x4i3 ?

**Comment by brown170** [comment]
@julia-sprenger, x4i3 is a fork and I don't control it.  Eventually x4i should go on PyPI, but I don't feel it or the NRDC are ready for it.

**Comment by julia-sprenger** [comment]
With the current setup of listing the requirements separately in the `requirements.txt` those are not detected when building the package for publication on PyPI. Currently no dependencies are included in the packaged version. For [the publish workflow](.github/workflows/python-publish.yml) to work correctly this would need to be fixed.

**Comment by brown170** [comment]
@julia-sprenger's merge request resolved this issue
