### ISSUE TITLE
Proposed tweaks to install.py

### ISSUE THREAD

**Issue by mattooca** [brown170/x4i#6]
Installation initially failed for me, probably due to firewall issue.  I was able to continue by manually downloading from IAEA and continuing the install process.

Proposed changes to install.py (extension renamed to .txt) would detect this and print guidance for continuing.  With these changes, on my system it prints
```

 ERROR encountered while downloading the EXFOR database:
   <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1076)>


As an alternative, please manually download the database zip file from https://www-nds.iaea.org/exfor-master/x4toc4/X4-2021-03-08.zip,
place it in the x4i directory and issue the following command (this takes a while):

./bin/setup-exfor-db.py --x4c4-master X4-2021-03-08.zip

Once that command finishes, X4-2021-03-08.zip can be safely deleted.
```

[install.txt](https://github.com/brown170/x4i/files/9668647/install.txt)

**Comment by brown170** [comment]
Implemented!  Thank you Caleb!
