### ISSUE TITLE
Use EXFOR dictionary project 

### ISSUE THREAD

**Issue by brown170** [brown170/x4i#8]
Shin Okumura is posting the latest dictionaries at https://github.com/IAEA-NDS/exfor_dictionary, we need to take from this rather than the old dicts used in the original project.

**Comment by brown170** [comment]
Now use "official" version at https://www-nds.iaea.org/nrdc/file/dson.html which is built from the dictionary project I believe

**Comment by julia-sprenger** [comment]
@brown170 Did you get confirmation that this "official" json version is updated whenever the regular dictionary files are updated? Otherwise it might be more maintainable to use an automatically generated full json version, e.g like the one linked in your first comment.
